SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

# asteroid settings
ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

# player settings
PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 250
PLAYER_SPEED = 200
PLAYER_SHOT_COOL_DOWN = 0.3

# shot settings
SHOT_RADIUS = 5
SHOOT_SPEED = 500
